server:
  port: 4060

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: hackcity
    url: jdbc:mysql://139.224.37.184:3309/buffalo?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
  elasticjob:
    zookeeper:
      server-lists: 127.0.0.1:2181
      namespace: buflo-daemon
